name: CI/CD counter app
on:
  push:
    branches: [ smit ]
      
jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            SOURCE : "DummyFolder/test.py"
            DESTINATION : "C:/demo"
            
        run: |
          cd ~/.ssh/
          ls
        # echo "-------------privatekey gen---------------"
        # echo "$PRIVATE_KEY" > id_rsa && sudo chmod 400 id_rsa
        # sudo ssh -o StrictHostKeyChecking=no -i id_rsa ${USER_NAME}@${HOSTNAME} 
        # echo "--------------list--------------------"
        # ls
        # echo "------------pwd------------------"
        # pwd
        # echo "------------scp--------------"
        # scp -o StrictHostKeyChecking=no ${SOURCE} ${USER_NAME}@${{secrets.AWS_DNS}}:/home/ubuntu/test/
# sshpass -p ${PASSWORD} ssh ${USER_NAME}@${HOSTNAME}
# sshpass -p ${PASSWORD} scp ${SOURCE} ${USER_NAME}@${HOSTNAME}:${DESTINATION}
# echo $SOURCE" : is SuccessFully Uploaded"
# echo "$PRIVATE_KEY" > key.pem
# sudo chmod 400 key.pem
# sudo ssh -o StrictHostKeyChecking=no -i key.pem ${USER_NAME}@${HOSTNAME} 
# scp -o StrictHostKeyChecking=no -i key.pem ${LOCALFILENAME} ${USER_NAME}@${HOSTNAME}:${DESTINATION}
# echo "File copyed successully in Server"${LOCALFILENAME}



          


