name: CI/CD counter app

on:
  push:
    branches: [ Master ]

jobs:

  Deploy:
    # needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            FILENAME : "DummyFolder/x"
            
        run: |
          echo "$PRIVATE_KEY" > key.pem
          ls
          sudo chmod 400 key.pem
          echo "-------ssh-------"
          sudo ssh -o StrictHostKeyChecking=no -i key.pem ${USER_NAME}@${HOSTNAME} 
          echo "------acp--------" 
          scp -o StrictHostKeyChecking=no -i key.pem -r DummyFolder ${USER_NAME}@${{secrets.AWS_DNS}}:/home/ubuntu/test/
          
          


