name: CI/CD counter app
on:
  push:
    branches: [ smit ]
      
jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            SOURCE : "DummyFolder/test.py"
            DESTINATION : "C:/demo"
            
        run: |
          echo "$PRIVATE_KEY" > id_rsa && sudo chmod 400 id_rsa
          scp -o StrictHostKeyChecking=no -i id_rsa ${SOURCE} ${USER_NAME}@${HOSTNAME}:${DESTINATION}

