name: CI/CD counter app

on:
  pull_request:
    types:
      - closed
      
jobs:
  Deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            LOCALFILENAME : "DummyFolder/1132"
            DESTINATION : "~/test/"
            
        run: |
          
          sudo chmod 400 ${PRIVATE_KEY}
          sudo ssh -o StrictHostKeyChecking=no -i key.pem ${USER_NAME}@${HOSTNAME} 
          scp -o StrictHostKeyChecking=no -i key.pem ${LOCALFILENAME} ${USER_NAME}@${HOSTNAME}:${DESTINATION}
          echo "File copyed successully in Server"${LOCALFILENAME}
