name: CI/CD counter app

on:
  push:
    branches: [ Master ]

jobs:

  Deploy:
    # needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key 
          ls
          echo "--------------"
          pwd
          echo "-----c---------"
          cat private_key
          sudo chmod 400 private_key
          echo "-------ssh-------"
          sudo ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} 
          echo "------acp--------" 
          scp -o StrictHostKeyChecking=no -i private_key -r Dummyfolder/ ${USER_NAME}@${{secrets.AWS_DNS}}:/home/ubuntu/test/
          
          


