name: CI/CD counter app

on:
  push:
    branches: [ Master ]

jobs:

  Deploy:
    # needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key 
          ls
          sudo chmod 400 private_key
          sudo ssh -i private_key ${USER_NAME}@${HOSTNAME} 

