name: CI/CD counter app
on:
  push:
    branches: [ smit ]
      
jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            LOCALFILENAME : "DummyFolder/ac"
            DESTINATION : "~/test/"
            
        run: |

          sudo chmod 400 ${$PRIVATE_KEY}
          sudo ssh  -i ${$PRIVATE_KEY} ${USER_NAME}@${HOSTNAME} 
          scp  -i ${$PRIVATE_KEY} ${LOCALFILENAME} ${USER_NAME}@${{secrets.AWS_DNS}}:${DESTINATION}
          echo "File copyed successully in Server"${LOCALFILENAME}


          # echo "$PRIVATE_KEY" > key.pem
          # sudo chmod 400 key.pem
          # sudo ssh  -i key.pem ${USER_NAME}@${HOSTNAME} 
          # scp  -i key.pem ${LOCALFILENAME} ${USER_NAME}@${{secrets.AWS_DNS}}:${DESTINATION}
          # echo "File copyed successully in Server"${LOCALFILENAME}
          


