name: CI/CD counter app

on:
  push: 

      
jobs:
  Deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            LOCALFILENAME : "DummyFolder/1132"
            DESTINATION : "~/test/"
            
        run: |

          sudo chmod 400 $PRIVATE_KEY
          echo "----------a-"
          sudo ssh -i $PRIVATE_KEY ${USER_NAME}@${HOSTNAME} 
          echo "----------b-"
          scp -i $PRIVATE_KEY ${LOCALFILENAME} ${USER_NAME}@${HOSTNAME}:${DESTINATION}
          echo "----------c-"
          echo "File copyed successully in Server"${LOCALFILENAME}
