name: CI/CD counter app
on:
  push:
    branches: [ smit ]
      
jobs:
  Deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            SOURCE : "DummyFolder/test.py"
            DESTINATION : "C:/demo"
            
        run: |
          echo "$PRIVATE_KEY" >> id_rsa
          echo "-----"
          pwd
          echo "-----"
          ls
          $path = ".\id_rsa"
          icacls.exe $path /reset
          icacls.exe $path /GRANT:R "$($env:USERNAME):(R)"
          icacls.exe $path /inheritance:r
          ls
          scp -o StrictHostKeyChecking=no -i id_rsa ${SOURCE} ${USER_NAME}@${HOSTNAME}:${DESTINN}


# icacls id_rsa /inheritance:r /grant "Administrators:F" /grant "SYSTEM:F"
