name: CI/CD counter app
on:
  push:
    branches: [ smit ]
      
jobs:
  Deploy:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2 
      
      
      - name: test
        run: |
          cd C:/ProgramData/ssh
          ls

      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            SOURCE : "DummyFolder/test.py"
            DESTINATION : "C:/demo"
            
        run: |
          Copy-Item -Path ${SOURCE} -Destination ${DESTINATION} -PassThru


# icacls id_rsa /inheritance:r /grant "Administrators:F" /grant "SYSTEM:F"
