name: CI/CD counter app

on:
  push:
    branches: [ dev ]

jobs:

  Deploy:
    # needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Create keypair
        run: |
          aws ec2 create-key-pair \
            --key-name private_key \
            --key-type rsa \
            --key-format pem \
            --query "KeyMaterial" \
            --output text > private_key.pem
      - name: Deploy in EC2
        env:
            # PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          sudo chmod 400 private_key
          sudo ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} 
          ls
          scp -o StrictHostKeyChecking=no -i private_key.pem package.json ${USER_NAME}@${{secrets.AWS_DNS}}:/home/ubuntu/test/
          