name: pythonj
on:
  workflow_dispatch:
  push:
    branches:
      - smit

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - run: |
          output=$(python test.py)
        id: step1
      - name: Print changelog
        run: echo "${{ steps.step1.outputs.changelog }}"